#!/bin/sh
# do not use this script in this form, 
# change (especially about authentication part) for meet your requirement..
git_user_name=$1
git_password=$2
git_repository=${3:--hostanamelist}
GITHUB=https://${git_user_name}:${git_password}@github.com/${git_user_name}/${git_repository}.git
WORKDIR=/var/tmp/fakedns/hostnamelist

if [ ! -d $WORKDIR ];then
	git clone $GITHUB $WORKDIR
else
	(cd $WORKDIR;git pull)
fi

cd $WORKDIR
git filter-branch -f --prune-empty --tree-filter 'if [ -e README.md ]; then rm -f hosts; fi' -- --all
git push --force

