#!/bin/sh
git_user_name=$1
git_password=$2
git_repository=${3:-hostanamelist}
GITHUB=https://${git_user_name}:${git_password}@github.com/${git_user_name}/${git_repository}.git
WORKDIR=/var/tmp/fakedns/hostnamelist

if [ ! -d $WORKDIR ];then
	git clone $GITHUB $WORKDIR
else
	(cd $WORKDIR;git pull)
fi

cat > $WORKDIR/hosts <<EOF_LISTHEAD
# The following list items will be updated when the computer is restarted(or when dhcp lease request is issued).  
# See https://gist.github.com/kurohara/5881858 for check your environment.  
EOF_LISTHEAD

sqlite3 /var/tmp/fakedns/dhcpdata.db >> $WORKDIR/hosts <<EOF_SQL
select ipaddr||'      '||hostname from maclist order by hostname;
EOF_SQL

cd $WORKDIR
git add hosts
git commit -m "hosts updated"
git push origin master

