#!/bin/sh
git_user_name=$1
git_password=$2
git_repository=${3:-hostanamelist}
GITHUB=https://${git_user_name}:${git_password}@github.com/${git_user_name}/${git_repository}.git
WORKDIR=/var/tmp/fakedns/hostnamelist

if [ ! -d $WORKDIR ];then
	git clone $GITHUB $WORKDIR
else
	(cd $WORKDIR;git pull)
fi

if [ -e $WORKDIR/hosts ];then
	cp $WORKDIR/hosts /etc/hosts
fi

